apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::886436935799:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-LR7vNJhatNP4
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::886436935799:role/FlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-12-17T11:15:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1361"
  uid: 31ea0ce1-5dfd-49a9-bc35-b3b380d1682a
